name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*        
          cache: yarn
      - name: install typescript dependencies
        shell: bash
        run: |
          yarn install --immutable
      - name: test the app
        shell: bash
        run: |
          yarn test
      - name: typecheck the app
        shell: bash
        # Using --noEmit because we only care about typechecking, not compiling
        run: |
          yarn run tsc --noEmit
      - name: lint the app
        shell: bash
        run: |
          yarn run eslint src
